#! /bin/bash
# chkconfig: 35 80 70
NODE_ENV=production
DAEMON="node /home/tony/mydisk/microblog/cluster.js"
NAME=Microblog
DESC=Microblog
PIDFILE="/home/tony/mydisk/microblog/microblog.pid"

case "$1" in 
  start)
    echo "Starting $DESC: "
      nohup $DAEMON > /dev/null &
    echo $! > $PIDFILE
    echo "$NAME."
        ;;
  stop)
    echo "Stopping $DESC: "  
    rm $PIDFILE
    kill -SIGKILL $(ps aux | grep 'cluster.js' | grep -v 'grep' | awk '{print $2}')
    echo "$NAME."
        ;;
esac
exit 0
